CREATE Table account(
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    secret VARCHAR(255) NOT NULL,
    Cpf VARCHAR(255) NOT NULL,
    Balance INT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
